title: FF8_demaster mod for FFVIII by Maki
description: Final Fantasy VIII Remastered game core mod which allows all texture replacement, fixes to original game and more!
google_analytics:
show_downloads: true

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
